version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - .:/go/src/go-sample
    ports:
      - 8080:8080
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: parks
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
