version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - .:/go/src/go-sample
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    hostname: db
    environment:
      MYSQL_DATABASE: parks
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
